# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Keelan Cook
subtitle: Missiologist
logo: "/assets/images/seal.png"
email: kcook@sebts.edu
description: >- # this means to ignore newlines until "baseurl:"
  The online home for Keelan Cook. Keelan is a missiologist who researches and writes on church and missions both in a North American and international context.
url: "keelancook.com"
twitter_username: keelancook
github_username: keelancook
minimal_mistakes_skin: air
search: true
teaser: /assets/images/teaser-image.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name   : "Keelan Cook"
  avatar : "/assets/images/headshots/keelan-headshot.jpg"
  bio    : "Keelan Cook is the George Liele Director for the Center for Great Commission Studies at Southeastern Baptist Theological Seminary where he serves as an instructor of Christian missions."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/keelancook"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/keelancook"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@keelan"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/keelancook"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@keelan"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/keelancook"

 
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-71XX5NEM31"
    anonymize_ip: false # default
